version: "3"

tasks:
  
  build:dev:
    desc: Build the project for testing in dev machine
    cmds:
      - go build -v -o luncher-dev
  
  build:target:
    desc: Build the project for target platform
    cmds:
      - GOOS=linux GOARCH=arm GOARM=7 go build -v
  
  run:dev:
    desc: Run the project for testing in dev machine
    cmds:
      - go run .
  
  deploy:target:
    desc: Deploy on the target node (Raspberry Pi Model 1B)
    cmds:
      - ssh -t pi@raspberrypi3 "docker stop luncher"
      - ssh -t pi@raspberrypi3 "docker rm luncher"
      - ssh -t pi@raspberrypi3 "docker prune"
      - ssh -t pi@raspberrypi3 "docker pull ghcr.io/rsora/luncher:latest"
      - ssh -t pi@raspberrypi3 "docker run --name luncher --restart=always -d -p 8000:8000 ghcr.io/rsora/luncher:latest"
      - sleep 5
      - curl raspberrypi3:8000/status
  # mount -o remount,rw /dev/block/mmcblk0p5 /system to unlock configuration stored in protected file system in NST
  ssh:nook:
    desc: Open SSH shell on the Nook Simple Touch (require ssh key)
    cmds:
      - ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 ${NOOK_IP} -l root
    env:
      # the command scans the both wifi and LAN and search for MAC prefix 58:67:1A
      # that should be the NOOK MAC prefix and returns the IP, because setting a hostname on the nook seems to be impossible
      NOOK_IP: $(sudo nmap -sn 192.168.1.0/24 | awk '/Nmap scan report/{printf $5;printf " ";getline;getline;print $3;}' | grep -F "58:67:1A" | cut -d" " -f1)


  ssh:rpi3:
    desc: Open SSH shell on the Raspberry Pi 3 (require ssh key)
    cmds:
      - ssh pi@raspberrypi3