version: "3"

tasks:
  
  build:dev:
    desc: Build the project for testing in dev machine
    cmds:
      - go build -v -o luncher-dev
  
  build:target:
    desc: Build the project for target platform
    cmds:
      - GOOS=linux GOARCH=arm GOARM=7 go build -v
  
  run:dev:
    desc: Run the project for testing in dev machine
    cmds:
      - go run .
  
  deploy:target:
    desc: Deploy on the target node (Raspberry Pi Model 1B)
    cmds:
      - task: build:target
      - ssh -t pi@raspberrypi3 "killall -q luncher || echo 'Process was not running.'"
      - scp luncher pi@raspberrypi3:/home/pi/luncher
      - ssh pi@raspberrypi3 "nohup /home/pi/luncher > /dev/null 2>&1 &"
      - sleep 1
      - curl raspberrypi3:8000/status