FROM balenalib/raspberry-pi-debian-golang:latest

WORKDIR /go/src/app
COPY . .

RUN go build -v -o luncher ./app/services/luncher
RUN go install -v ./app/services/luncher

EXPOSE 8000

CMD ["luncher"]